[workspace]
resolver = "2"
members = ["crates/mage", "crates/mage-ast", "crates/mage-compiler", "crates/mage-contract", "crates/mage-loader", "crates/mage-native", "crates/mage-da", "crates/mage-ls", "crates/mage-memory", "crates/serde_text", "crates/serde_text_derive"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
strip = true
