// Code generated by build.js from template_test.ejs and bytecode.yaml. DO NOT EDIT.

use crate::*;

fn encode(instructions: &[Instruction]) -> Vec<u8> {
    let mut writer = Writer::new();
    for instruction in instructions {
        writer.write(instruction);
    }
    writer.bytecode
}

fn assert_round_trip(instructions: &[Instruction]) {
    let original = encode(instructions);

    for format in [Format::Simple, Format::Pretty] {
        let reader = Reader::new(&original).unwrap();
        let text = if matches!(format, Format::Pretty) {
            serde_text::to_string_pretty(&reader)
        } else {
            serde_text::to_string(&reader)
        };

        let reconstructed = Writer::from_text(&text).unwrap();

        assert_eq!(
            original, reconstructed,
            "round-trip mismatch ({:?} format).\n--- text ---\n{}",
            format, text,
        );
    }
}

fn assert_json_round_trip(instructions: &[Instruction]) {
    let original = encode(instructions);

    let reader = Reader::new(&original).unwrap();
    let json = serde_json::to_string(&reader).unwrap();
    let reconstructed = Writer::from_json(&json).unwrap();

    assert_eq!(
        original, reconstructed,
        "JSON round-trip mismatch.\n--- json ---\n{}",
        json,
    );
}

#[test]
fn encoder_empty_bytecode() {
    let reader = Reader::new(&[]).unwrap();
    assert_eq!(reader.instruction_count(), 0);
    assert_eq!(reader.bytecode_size(), 0);
    let output = serde_text::to_string_pretty(&reader);
    assert!(output.contains("(empty)"));
}

#[test]
fn encoder_single_exit() {
    let bytecode = encode(&[Instruction::ExitCodeImmutable(ExitCodeImmutable {
        code: 0,
    })]);

    let reader = Reader::new(&bytecode).unwrap();
    assert_eq!(reader.instruction_count(), 1);
    assert_eq!(reader.bytecode_size(), 16);

    let output = serde_text::to_string_pretty(&reader);
    assert!(output.contains("Exit"));
    assert!(output.contains("code:i0"));
}

#[test]
fn encoder_exit_offset_variant() {
    let bytecode = encode(&[
        Instruction::TakeStackSizeImmutable(TakeStackSizeImmutable { stack_size: 8 }),
        Instruction::ExitCodeOffset(ExitCodeOffset { code: 0 }),
    ]);

    let reader = Reader::new(&bytecode).unwrap();
    let output = serde_text::to_string_pretty(&reader);
    assert!(output.contains("Exit"));
    assert!(output.contains("code:o0"));
}

#[test]
fn encoder_pretty_alignment() {
    let bytecode = encode(&[
        Instruction::TakeStackSizeImmutable(TakeStackSizeImmutable { stack_size: 48 }),
        Instruction::JumpToImmutable(JumpToImmutable { to: 40 }),
        Instruction::ExitCodeOffset(ExitCodeOffset { code: 0 }),
        Instruction::LoadTargetOffsetSourceImmutable(LoadTargetOffsetSourceImmutable {
            target: 48,
            source: 0,
        }),
        Instruction::FreeStackSizeImmutable(FreeStackSizeImmutable { stack_size: 48 }),
        Instruction::JumpToImmutable(JumpToImmutable { to: 24 }),
    ]);

    let reader = Reader::new(&bytecode).unwrap();
    let output = serde_text::to_string_pretty(&reader);

    let lines: Vec<&str> = output.lines().collect();
    assert_eq!(lines.len(), 6);

    assert!(lines[0].starts_with("000"));
    assert!(lines[1].starts_with("016"));
    assert!(lines[2].starts_with("032"));
    assert!(lines[3].starts_with("048"));
    assert!(lines[4].starts_with("072"));
    assert!(lines[5].starts_with("088"));
}

#[test]
fn encoder_simple_no_padding() {
    let bytecode = encode(&[Instruction::ExitCodeImmutable(ExitCodeImmutable {
        code: 42,
    })]);

    let pretty = Reader::new(&bytecode).unwrap();
    let simple = Reader::new(&bytecode).unwrap();

    let pretty_output = serde_text::to_string_pretty(&pretty);
    let simple_output = serde_text::to_string(&simple);

    assert!(pretty_output.contains("Exit"));
    assert!(simple_output.contains("Exit"));
    assert!(pretty_output.contains("code:i42"));
    assert!(simple_output.contains("code:i42"));
}

#[test]
fn encoder_operand_kinds_distinguished() {
    let bytecode = encode(&[
        Instruction::LoadTargetOffsetSourceOffset(LoadTargetOffsetSourceOffset {
            target: 0,
            source: 8,
        }),
        Instruction::LoadTargetOffsetSourceImmutable(LoadTargetOffsetSourceImmutable {
            target: 0,
            source: 42,
        }),
        Instruction::ExitCodeImmutable(ExitCodeImmutable { code: 0 }),
    ]);

    let reader = Reader::new(&bytecode).unwrap();
    let output = serde_text::to_string(&reader);
    let lines: Vec<&str> = output.lines().collect();

    assert!(lines[0].contains("target:o0"));
    assert!(lines[0].contains("source:o8"));

    assert!(lines[1].contains("target:o0"));
    assert!(lines[1].contains("source:i42"));
}

#[test]
fn encoder_decode_invalid_bytecode_fails() {
    let bad = vec![0xFF; 8];
    let result = Reader::new(&bad);
    assert!(result.is_err());
}


#[test]
fn round_trip_empty() {
    let text = Writer::from_text("").unwrap();
    assert!(text.is_empty());

    let text = Writer::from_text("(empty)\n").unwrap();
    assert!(text.is_empty());
}

#[test]
fn round_trip_none() {
    assert_round_trip(&[
        Instruction::None,
    ]);
}

#[test]
fn round_trip_exit_code_immutable() {
    assert_round_trip(&[
        Instruction::ExitCodeImmutable(ExitCodeImmutable {
            code: 1,
        }),
    ]);
}

#[test]
fn round_trip_exit_code_offset() {
    assert_round_trip(&[
        Instruction::ExitCodeOffset(ExitCodeOffset {
            code: 0,
        }),
    ]);
}

#[test]
fn round_trip_take_stack_size_immutable() {
    assert_round_trip(&[
        Instruction::TakeStackSizeImmutable(TakeStackSizeImmutable {
            stack_size: 1,
        }),
    ]);
}

#[test]
fn round_trip_free_stack_size_immutable() {
    assert_round_trip(&[
        Instruction::FreeStackSizeImmutable(FreeStackSizeImmutable {
            stack_size: 1,
        }),
    ]);
}

#[test]
fn round_trip_load_target_offset_source_offset() {
    assert_round_trip(&[
        Instruction::LoadTargetOffsetSourceOffset(LoadTargetOffsetSourceOffset {
            target: 0,
            source: 8,
        }),
    ]);
}

#[test]
fn round_trip_load_target_offset_source_immutable() {
    assert_round_trip(&[
        Instruction::LoadTargetOffsetSourceImmutable(LoadTargetOffsetSourceImmutable {
            target: 0,
            source: 2,
        }),
    ]);
}

#[test]
fn round_trip_add_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::AddTargetOffsetLeftOffsetRightOffset(AddTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_add_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::AddTargetOffsetLeftOffsetRightImmutable(AddTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_subtract_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::SubtractTargetOffsetLeftOffsetRightOffset(SubtractTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_subtract_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::SubtractTargetOffsetLeftOffsetRightImmutable(SubtractTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_multiply_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::MultiplyTargetOffsetLeftOffsetRightOffset(MultiplyTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_multiply_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::MultiplyTargetOffsetLeftOffsetRightImmutable(MultiplyTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_divide_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::DivideTargetOffsetLeftOffsetRightOffset(DivideTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_divide_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::DivideTargetOffsetLeftOffsetRightImmutable(DivideTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_modulo_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::ModuloTargetOffsetLeftOffsetRightOffset(ModuloTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_modulo_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::ModuloTargetOffsetLeftOffsetRightImmutable(ModuloTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_less_than_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::LessThanTargetOffsetLeftOffsetRightOffset(LessThanTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_less_than_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::LessThanTargetOffsetLeftOffsetRightImmutable(LessThanTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_greater_than_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::GreaterThanTargetOffsetLeftOffsetRightOffset(GreaterThanTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_greater_than_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::GreaterThanTargetOffsetLeftOffsetRightImmutable(GreaterThanTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_less_than_or_equal_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::LessThanOrEqualTargetOffsetLeftOffsetRightOffset(LessThanOrEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_less_than_or_equal_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::LessThanOrEqualTargetOffsetLeftOffsetRightImmutable(LessThanOrEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_greater_than_or_equal_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::GreaterThanOrEqualTargetOffsetLeftOffsetRightOffset(GreaterThanOrEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_greater_than_or_equal_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::GreaterThanOrEqualTargetOffsetLeftOffsetRightImmutable(GreaterThanOrEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_equal_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::EqualTargetOffsetLeftOffsetRightOffset(EqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_equal_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::EqualTargetOffsetLeftOffsetRightImmutable(EqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_not_equal_target_offset_left_offset_right_offset() {
    assert_round_trip(&[
        Instruction::NotEqualTargetOffsetLeftOffsetRightOffset(NotEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn round_trip_not_equal_target_offset_left_offset_right_immutable() {
    assert_round_trip(&[
        Instruction::NotEqualTargetOffsetLeftOffsetRightImmutable(NotEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn round_trip_jump_to_immutable() {
    assert_round_trip(&[
        Instruction::JumpToImmutable(JumpToImmutable {
            to: 1,
        }),
    ]);
}

#[test]
fn round_trip_jump_to_offset() {
    assert_round_trip(&[
        Instruction::JumpToOffset(JumpToOffset {
            to: 0,
        }),
    ]);
}

#[test]
fn round_trip_jump_if_not_condition_offset_to_immutable() {
    assert_round_trip(&[
        Instruction::JumpIfNotConditionOffsetToImmutable(JumpIfNotConditionOffsetToImmutable {
            condition: 0,
            to: 2,
        }),
    ]);
}

#[test]
fn round_trip_jump_if_condition_offset_to_immutable() {
    assert_round_trip(&[
        Instruction::JumpIfConditionOffsetToImmutable(JumpIfConditionOffsetToImmutable {
            condition: 0,
            to: 2,
        }),
    ]);
}

#[test]
fn text_decode_unknown_instruction_is_error() {
    let result = Writer::from_text("000 BogusInstruction\n");
    assert!(result.is_err());
    if let Err(ParseError::UnknownInstruction { name, .. }) = &result {
        assert_eq!(name, "BogusInstruction");
    } else {
        panic!("expected UnknownInstruction, got {:?}", result);
    }
}

#[test]
fn text_decode_invalid_operand_is_error() {
    let result = Writer::from_text("000 Exit code:x42\n");
    assert!(result.is_err());
}

#[test]
fn text_decode_skips_blank_lines() {
    let text = "\n\n000 Exit code:i0\n\n";
    let bytecode = Writer::from_text(text).unwrap();
    let expected = encode(&[Instruction::ExitCodeImmutable(ExitCodeImmutable {
        code: 0,
    })]);
    assert_eq!(bytecode, expected);
}

#[test]
fn json_round_trip_empty() {
    assert_json_round_trip(&[]);
}

#[test]
fn json_round_trip_none() {
    assert_json_round_trip(&[
        Instruction::None,
    ]);
}

#[test]
fn json_round_trip_exit_code_immutable() {
    assert_json_round_trip(&[
        Instruction::ExitCodeImmutable(ExitCodeImmutable {
            code: 1,
        }),
    ]);
}

#[test]
fn json_round_trip_exit_code_offset() {
    assert_json_round_trip(&[
        Instruction::ExitCodeOffset(ExitCodeOffset {
            code: 0,
        }),
    ]);
}

#[test]
fn json_round_trip_take_stack_size_immutable() {
    assert_json_round_trip(&[
        Instruction::TakeStackSizeImmutable(TakeStackSizeImmutable {
            stack_size: 1,
        }),
    ]);
}

#[test]
fn json_round_trip_free_stack_size_immutable() {
    assert_json_round_trip(&[
        Instruction::FreeStackSizeImmutable(FreeStackSizeImmutable {
            stack_size: 1,
        }),
    ]);
}

#[test]
fn json_round_trip_load_target_offset_source_offset() {
    assert_json_round_trip(&[
        Instruction::LoadTargetOffsetSourceOffset(LoadTargetOffsetSourceOffset {
            target: 0,
            source: 8,
        }),
    ]);
}

#[test]
fn json_round_trip_load_target_offset_source_immutable() {
    assert_json_round_trip(&[
        Instruction::LoadTargetOffsetSourceImmutable(LoadTargetOffsetSourceImmutable {
            target: 0,
            source: 2,
        }),
    ]);
}

#[test]
fn json_round_trip_add_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::AddTargetOffsetLeftOffsetRightOffset(AddTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_add_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::AddTargetOffsetLeftOffsetRightImmutable(AddTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_subtract_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::SubtractTargetOffsetLeftOffsetRightOffset(SubtractTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_subtract_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::SubtractTargetOffsetLeftOffsetRightImmutable(SubtractTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_multiply_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::MultiplyTargetOffsetLeftOffsetRightOffset(MultiplyTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_multiply_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::MultiplyTargetOffsetLeftOffsetRightImmutable(MultiplyTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_divide_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::DivideTargetOffsetLeftOffsetRightOffset(DivideTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_divide_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::DivideTargetOffsetLeftOffsetRightImmutable(DivideTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_modulo_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::ModuloTargetOffsetLeftOffsetRightOffset(ModuloTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_modulo_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::ModuloTargetOffsetLeftOffsetRightImmutable(ModuloTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_less_than_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::LessThanTargetOffsetLeftOffsetRightOffset(LessThanTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_less_than_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::LessThanTargetOffsetLeftOffsetRightImmutable(LessThanTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_greater_than_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::GreaterThanTargetOffsetLeftOffsetRightOffset(GreaterThanTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_greater_than_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::GreaterThanTargetOffsetLeftOffsetRightImmutable(GreaterThanTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_less_than_or_equal_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::LessThanOrEqualTargetOffsetLeftOffsetRightOffset(LessThanOrEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_less_than_or_equal_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::LessThanOrEqualTargetOffsetLeftOffsetRightImmutable(LessThanOrEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_greater_than_or_equal_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::GreaterThanOrEqualTargetOffsetLeftOffsetRightOffset(GreaterThanOrEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_greater_than_or_equal_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::GreaterThanOrEqualTargetOffsetLeftOffsetRightImmutable(GreaterThanOrEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_equal_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::EqualTargetOffsetLeftOffsetRightOffset(EqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_equal_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::EqualTargetOffsetLeftOffsetRightImmutable(EqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_not_equal_target_offset_left_offset_right_offset() {
    assert_json_round_trip(&[
        Instruction::NotEqualTargetOffsetLeftOffsetRightOffset(NotEqualTargetOffsetLeftOffsetRightOffset {
            target: 0,
            left: 8,
            right: 16,
        }),
    ]);
}

#[test]
fn json_round_trip_not_equal_target_offset_left_offset_right_immutable() {
    assert_json_round_trip(&[
        Instruction::NotEqualTargetOffsetLeftOffsetRightImmutable(NotEqualTargetOffsetLeftOffsetRightImmutable {
            target: 0,
            left: 8,
            right: 3,
        }),
    ]);
}

#[test]
fn json_round_trip_jump_to_immutable() {
    assert_json_round_trip(&[
        Instruction::JumpToImmutable(JumpToImmutable {
            to: 1,
        }),
    ]);
}

#[test]
fn json_round_trip_jump_to_offset() {
    assert_json_round_trip(&[
        Instruction::JumpToOffset(JumpToOffset {
            to: 0,
        }),
    ]);
}

#[test]
fn json_round_trip_jump_if_not_condition_offset_to_immutable() {
    assert_json_round_trip(&[
        Instruction::JumpIfNotConditionOffsetToImmutable(JumpIfNotConditionOffsetToImmutable {
            condition: 0,
            to: 2,
        }),
    ]);
}

#[test]
fn json_round_trip_jump_if_condition_offset_to_immutable() {
    assert_json_round_trip(&[
        Instruction::JumpIfConditionOffsetToImmutable(JumpIfConditionOffsetToImmutable {
            condition: 0,
            to: 2,
        }),
    ]);
}

